version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:4.1.1-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - dead_letter_net
  
  app:
    build: .
    networks:
      - dead_letter_net


volumes:
  rabbitmq_data:

networks:
  dead_letter_net:
